--- #YAML:1.0
name:               HTML-Tested-JavaScript
version:            0.28
abstract:           HTML::Tested JavaScript helpers
author:
    - Boris Sukholitko (boriss@gmail.com)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Slurp:          
    Gtk2::WebKit::Mechanize:  
    HTML::Tested:         0.56
    HTTP::Daemon:         
    HTTP::Request::Params:  
    JSON::XS:             
    Mozilla::Mechanize::GUITester:  0.18
    Mozilla::SourceViewer:  0.05
    Test::Simple:         0.44
    Text::Diff:           
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
