# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Tested-JavaScript
version:      0.01
version_from: lib/HTML/Tested/JavaScript.pm
installdirs:  site
requires:
    File::Slurp:                   
    HTML::Tested:                  0.2
    Mozilla::Mechanize::GUITester: 0.08
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
