--- #YAML:1.0
name:                HTML-Tested-JavaScript
version:             0.14
abstract:            HTML::Tested JavaScript helpers
license:             ~
author:              
    - Boris Sukholitko (boriss@gmail.com)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Slurp:                   
    HTML::Tested:                  0.48
    HTTP::Daemon:                  
    HTTP::Request::Params:         
    Mozilla::Mechanize::GUITester: 0.17
    Mozilla::SourceViewer:         0.05
    Test::Simple:                  0.44
    Text::Diff:                    
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
